apiVersion: v2
name: steadybit-extension-http
description: Steadybit action implementation to check HTTP endpoints.
version: 1.1.18
appVersion: v1.0.24
home: https://www.steadybit.com/
icon: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
maintainers:
  - email: ansgar.schulte@steadybit.com
    name: ansgarschulte
sources:
  - https://github.com/steadybit/extension-http
annotations:
  artifacthub.io/images: |
    - name: logo
      image: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
  artifacthub.io/links: |-
    - name: Steadybit website
      url: https://www.steadybit.com
    - name: Steadybit reliability hub
      url: https://hub.steadybit.com
dependencies:
  - name: extensionlib
    version: ^1.4.4
    repository: https://steadybit.github.io/helm-charts
